version: "3"
services:
  intermine_builder:
    container_name: intermine_builder
    build:
      context: ./intermine_builder
      dockerfile: ./intermine_builder.Dockerfile
    volumes:
      - ./data/mine/data:/home/intermine/intermine/data
      - ./data/mine/dump:/home/intermine/intermine/dump
      - ./data/mine/configs:/home/intermine/intermine/configs
      # - ./data/mine/[PUT_YOUR_MINE_NAME_HERE]:/home/intermine/intermine/[PUT_YOUR_MINE_NAME_HERE]
    environment:
      - MINE_NAME=${MINE_NAME:-biotestmine}
      - MINE_REPO_URL=${MINE_REPO_URL:-}
      - IM_DATA_DIR=${IM_DATA_DIR:-DATA_DIR}
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1g"}
    depends_on: 
      - postgres
      - solr
      - tomcat

  postgres:
    container_name: intermine_postgres
    build:
      context: ./postgres
      dockerfile: ./postgres.Dockerfile
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  solr:
    container_name: intermine_solr
    build:
      context: ./solr
      dockerfile: ./solr.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1g"}
      - MINE_NAME=${MINE_NAME:-biotestmine}
    volumes:
      - ./data/solr:/var/solr

  tomcat:
    container_name: intermine_tomcat
    build:
      context: ./tomcat
      dockerfile: ./tomcat.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx1g -Xms500m"}
    ports:
      - ${TOMCAT_HOST_PORT:-9999}:${TOMCAT_PORT:-8080}

# volumes:
#   PostgresDBData:
#   SolrDBData:
#   MineData:
#   MineConfigs: